databases:
  - name: geeklogistics_DB
    databaseName:  geeklogistics_db
    user: geeklogistics
    region: singapore

services:
  - type: web
    name: geeklogistics
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: geeklogistics_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
